### ISSUE TITLE
502 Errors when opcache enabled?

### ISSUE THREAD

**Issue by tommymarshall** [roots/bedrock-capistrano#6]
Love what you guys are doing. Quick question regarding an issue we're getting... apologies if this is the wrong repo to post the issue.

Whenever we do a deploy, we noticed we'll started getting some 502 errors when attempting to save settings within WP or visiting certain pages on the frontend. It also seems that our caching plugin (w3totalcache) stops working (the cache directory is in the old release folder). It seems that opcache doesn't like when we've symlinked to the new release folder. Have you experienced this? Is there a better workaround than simply disabling opcache? Is it expected to restart nginx upon deploy, or something else I'm missing?

Thanks for any help you can lend!

**Comment by swalkinshaw** [comment]
Yeah that's expected behaviour unfortunately.

Two things you should do during deploys:
1. `nginx reload` (NOT `restart`)
2. `php-fpm reload`

See http://stackoverflow.com/questions/19808884/nginx-and-or-php5-fpm-remembers-symlinked-root-directory for example.

And if you're using Nginx then make you have this:

``` nginx
fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
fastcgi_param DOCUMENT_ROOT $realpath_root;
```
